#!/usr/bin/env node
// Focused DOM-free regressions for click spells, temporary consumables, summons, and enemy pickup.

import assert from "node:assert/strict";
import * as sim from "../src/game/simulation.js";
import * as data from "../src/game/data.js";
import {cardById} from "../src/game/cards.js";

sim.initializeRunMode("normal");sim.debugClearHand();
sim.trees.length=sim.rocks.length=sim.diamonds.length=sim.chests.length=sim.buildings.length=sim.friendlyBrutes.length=sim.state.enemies.length=sim.resourceDrops.length=0;
const counts=()=>Object.fromEntries(data.RESOURCE_KINDS.map(kind=>[kind,0]));
const worker=(x,y)=>({x,y,postX:x,postY:y,spawnSource:null,job:"guard",jobTarget:null,autonomous:false,taskTarget:null,selfSupply:null,returning:false,starved:false,carried:counts(),hp:data.WORKER_HP,attackCooldown:0,hitCooldown:.5,step:0,combatTarget:null,retaliationTarget:null,returnAfterCombat:false,fleeing:false,fleeSafeTime:0});
const drop=(kind,x,y)=>({kind,x,y,groundY:y,vx:0,vy:0,ground:true,target:null,t:0,spin:0,ttl:null});
const play=id=>{assert.equal(sim.debugDealCard(id),true);return sim.playCard(sim.hand().findIndex(entry=>entry.id===id));};
const findAnchor=(type=sim.state.buildMode,exclude=null)=>{for(let y=96;y<data.H-96;y+=data.CELL)for(let x=96;x<data.W-96;x+=data.CELL)if((!exclude||x!==exclude.x||y!==exclude.y)&&sim.canPlace(x,y,type))return {x,y};assert.fail("no placement anchor for "+type);};
const place=id=>{assert.equal(play(id),"targeting");const anchor=findAnchor();sim.setPointerWorld(anchor.x,anchor.y);sim.primaryPress();sim.primaryRelease();return anchor;};
const findWater=()=>{for(let y=96;y<data.H-96;y+=data.CELL)for(let x=96;x<data.W-96;x+=data.CELL)if(sim.terrainAtWorldPoint(x,y)==="water")return {x,y};assert.fail("no water cell");};
const originalRandom=Math.random;Math.random=()=>0;
let visible=new Set(),levelEvents=0;sim.connect({isCombatTargetOnScreen(target){return visible.has(target);},levelChanged(){levelEvents++;}});

// Free Hit is bounded, and a free hit generated by a chain jump may start its own chain.
sim.spawnEnemy("raider");let enemy=sim.state.enemies[0];enemy.x=data.BASE.x+100;enemy.y=data.BASE.y;sim.debugApplyBuff("freeHit");sim.TUNE.chopTime=.01;
sim.setPointerWorld(enemy.x,enemy.y);sim.primaryPress();sim.update(.02);sim.primaryRelease();assert.equal(enemy.hp,3,"Free Hit must strike exactly once without recursive Free Hits");
sim.state.enemies.length=0;sim.lightningArcs.length=0;sim.spawnEnemy("brute");sim.spawnEnemy("brute");let [chainA,chainB]=sim.state.enemies;chainA.x=data.BASE.x+100;chainA.y=data.BASE.y;chainB.x=chainA.x+60;chainB.y=chainA.y;sim.debugApplyBuff("chainLightning");
sim.setPointerWorld(chainA.x,chainA.y);sim.primaryPress();sim.update(.02);sim.primaryRelease();assert.ok(sim.lightningArcs.length>1&&sim.lightningArcs.length<=24,"generated hit effects must compose but remain depth-bounded");delete sim.state.draft.buffs.chainLightning;delete sim.state.draft.buffs.freeHit;

// Screen spells consume an injected active-camera answer, not simulation camera approximations.
sim.state.enemies.length=0;sim.spawnEnemy("brute");sim.spawnEnemy("brute");let [near,far]=sim.state.enemies;visible=new Set([near]);const farHp=far.hp;
assert.equal(play("screenClick"),"applied");assert.equal(near.hp,near.max-1);assert.equal(far.hp,farHp);assert.equal(play("touchOfDeath"),"applied");assert.equal(sim.state.enemies.includes(near),false);assert.equal(far.hp,farHp);

// Recall releases claims and batches all arrivals through feedBase: XP changes once, storage never does.
sim.resourceDrops.length=0;const recallA=drop("wood",100,100),recallB=drop("stone",132,100),claimer=worker(100,100);claimer.taskTarget=recallA;recallA.claimedBy=claimer;sim.state.workers.push(claimer);sim.resourceDrops.push(recallA,recallB);
const xpBefore=sim.xp(),storedBefore={...sim.state.stored},eventsBefore=levelEvents;assert.equal(play("resourceRecall"),"applied");assert.equal(claimer.taskTarget,null);sim.update(1);
assert.equal(sim.resourceDrops.length,0);assert.equal(sim.xp(),xpBefore+2);assert.deepEqual(sim.state.stored,storedBefore);assert.equal(levelEvents,eventsBefore+1,"one recall frame must create one feed transaction");sim.state.workers.length=0;

// Meteor rejects water, respects occupancy/radius, installs a validated 3x3 rock, and can be mined out.
assert.equal(play("meteor"),"targeting");const water=findWater(),meteorAnchor=findAnchor();sim.setPointerWorld(water.x,water.y);sim.primaryPress();sim.primaryRelease();assert.ok(sim.hand().some(entry=>entry.id==="meteor"),"invalid cast spent meteor");
sim.spawnEnemy("brute");sim.spawnEnemy("brute");const [edge,outside]=sim.state.enemies.slice(-2);edge.x=meteorAnchor.x+data.METEOR.radius;edge.y=meteorAnchor.y;outside.x=edge.x+1;outside.y=edge.y;const outsideHp=outside.hp;
sim.setPointerWorld(meteorAnchor.x,meteorAnchor.y);sim.primaryPress();sim.primaryRelease();const meteorRock=sim.rocks.at(-1);assert.equal(edge.hp,Math.max(0,edge.max-data.METEOR.damage));assert.equal(outside.hp,outsideHp);assert.equal(meteorRock.meteor,true);assert.equal(meteorRock.footprint,data.FOOTPRINT_3x3);assert.equal(sim.canPlace(meteorAnchor.x,meteorAnchor.y,"meteorTarget"),false);
for(let i=0;i<data.METEOR.rockHp;i++){sim.setPointerWorld(meteorRock.x,meteorRock.y);sim.primaryPress();sim.update(.02);sim.primaryRelease();}assert.equal(meteorRock.depleted,1);assert.equal(meteorRock.hp,0);sim.state.enemies.length=0;sim.validateSimulationInvariants();

// Three orbs independently cover their orbit; relocation restores on water, pause freezes lifetime,
// held lifetime still expires, and ordinary expiry removes the center.
Math.random=()=>.999;const orbAnchor=place("damageOrbs"),orb=sim.buildings.find(building=>building.type==="damageOrbs");assert.equal(orb.orbs.count,3);
for(let i=0;i<3;i++){sim.spawnEnemy("brute");const target=sim.state.enemies.at(-1),a=i*Math.PI*2/3;target.x=orb.x+Math.cos(a)*data.DAMAGE_ORBS.orbitRadius;target.y=orb.y+Math.sin(a)*data.DAMAGE_ORBS.orbitRadius;}const orbVictims=[...sim.state.enemies],victimHp=orbVictims.map(target=>target.hp);sim.update(.001);orbVictims.forEach((target,i)=>assert.equal(target.hp,victimHp[i]-data.DAMAGE_ORBS.damage));sim.state.enemies.length=0;
const remaining=orb.orbs.remaining;sim.togglePause();sim.update(5);sim.togglePause();assert.equal(orb.orbs.remaining,remaining);
sim.setPointerWorld(orb.x,orb.y);sim.secondaryPress();assert.equal(sim.heldBuilding(),orb);const origin={x:orb.x,y:orb.y};sim.setPointerWorld(water.x,water.y);sim.secondaryRelease();assert.deepEqual({x:orb.x,y:orb.y},origin,"invalid relocation did not restore origin");
sim.setPointerWorld(orb.x,orb.y);sim.secondaryPress();const moved=findAnchor("damageOrbs",origin);sim.setPointerWorld(moved.x,moved.y);sim.secondaryRelease();assert.deepEqual({x:orb.x,y:orb.y},moved);orb.orbs.remaining=.01;sim.update(.02);assert.equal(sim.buildings.includes(orb),false);
const heldExpiryAnchor=place("damageOrbs"),heldExpiry=sim.buildings.find(building=>building.type==="damageOrbs");heldExpiry.orbs.remaining=.01;sim.setPointerWorld(heldExpiryAnchor.x,heldExpiryAnchor.y);sim.secondaryPress();sim.update(.02);assert.equal(sim.heldBuilding(),null,"held temporary survived expiry");

// Circle preserves partial dust through relocation, expires unfunded, consumes itself on exact need,
// drops excess dust, and creates an enemy-targetable defender that can die.
Math.random=()=>0;place("summoningCircle");const expiring=sim.buildings.find(building=>building.type==="summoningCircle");expiring.summoning.remaining=.01;sim.update(.02);assert.equal(sim.buildings.includes(expiring),false);
const circleAnchor=place("summoningCircle"),circle=sim.buildings.find(building=>building.type==="summoningCircle");sim.state.carried.dust=2;sim.setPointerWorld(circle.x,circle.y);sim.secondaryRelease();assert.equal(circle.summoning.dust,2);assert.equal(sim.buildings.includes(circle),true);
sim.setPointerWorld(circle.x,circle.y);sim.secondaryPress();const circleOrigin={x:circle.x,y:circle.y};sim.setPointerWorld(water.x,water.y);sim.secondaryRelease();assert.deepEqual({x:circle.x,y:circle.y},circleOrigin);assert.equal(circle.summoning.dust,2);
sim.setPointerWorld(circle.x,circle.y);sim.secondaryPress();const circleMoved=findAnchor("summoningCircle",circleOrigin);sim.setPointerWorld(circleMoved.x,circleMoved.y);sim.secondaryRelease();assert.deepEqual({x:circle.x,y:circle.y},circleMoved);assert.equal(circle.summoning.dust,2);
sim.resourceDrops.length=0;sim.state.carried.dust=5;sim.setPointerWorld(circle.x,circle.y);sim.secondaryRelease();assert.equal(sim.buildings.includes(circle),false,"funded circle was not consumed");assert.equal(sim.friendlyBrutes.length,1);assert.equal(sim.state.carried.dust,0);assert.equal(sim.resourceDrops.filter(item=>item.kind==="dust").length,2,"excess dust was not returned physically");
const defender=sim.friendlyBrutes[0];sim.resourceDrops.length=0;sim.spawnEnemy("bruteBoss");enemy=sim.state.enemies.at(-1);enemy.x=defender.x+20;enemy.y=defender.y;enemy.attackCooldown=0;const defenderHp=defender.hp;sim.DBG.invulnBase=true;sim.update(.01);assert.ok(defender.hp<defenderHp,"hostile did not target nearer friendly Brute");for(let i=0;i<20&&sim.friendlyBrutes.includes(defender);i++)sim.update(.2);assert.equal(sim.friendlyBrutes.includes(defender),false,"friendly Brute could not die");sim.state.enemies.length=0;

// Prerequisite gating is deterministic run state, not luck: a `requires` card is locked out of every
// eligible pool until each listed buff is owned, and unlocking never edits the authored catalog.
const gated=cardById.bpCaptureYard;
assert.deepEqual(gated.requires,["enemyPickup"]);
assert.equal(sim.buffStacks("enemyPickup"),0,"test order broke: enemyPickup owned before the gating checks");
assert.equal(sim.cardPrerequisitesMet(gated),false,"prerequisite reported met before its buff was owned");
assert.equal(sim.draftEligible().some(card=>!sim.cardPrerequisitesMet(card)),false,"eligible pool leaked a locked card");
assert.equal(sim.draftEligible(["build"]).some(card=>card.id===gated.id),false,"locked build card entered the level pool");

// Workers retain right-click priority over overlapping light enemies. Held scheduled enemies count
// toward clearance, preserve status, restore on cancel, reject water, and heavy enemies remain fixed.
sim.debugApplyBuff("enemyPickup");
assert.equal(sim.cardPrerequisitesMet(gated),true,"owning the buff did not satisfy the prerequisite");
assert.equal(sim.draftEligible(["build"]).some(card=>card.id===gated.id),gated.inPool,"unlocked eligibility must track the authored inPool flag alone");
assert.equal(gated.implemented||!gated.inPool,true,"bpCaptureYard may not enter the pool before its loop is implemented");const overlapWorker=worker(circleAnchor.x+200,circleAnchor.y);sim.state.workers.push(overlapWorker);sim.spawnEnemy("raider");enemy=sim.state.enemies.at(-1);enemy.x=overlapWorker.x;enemy.y=overlapWorker.y;sim.setPointerWorld(enemy.x,enemy.y);sim.secondaryPress();assert.equal(sim.heldWorker(),overlapWorker);sim.pointerCancelled();sim.state.workers.length=0;
if(sim.state.clock.phase==="day")sim.transitionPhase();enemy.waveNightNumber=sim.state.nightWave.activeNightNumber;enemy.status.slow={duration:2,multiplier:.5};enemy.attackCooldown=.7;const identity={status:enemy.status,hp:enemy.hp,cooldown:enemy.attackCooldown,x:enemy.x,y:enemy.y};
sim.setPointerWorld(enemy.x,enemy.y);sim.secondaryPress();assert.equal(sim.heldEnemy(),enemy);assert.equal(sim.livingActiveWaveEnemies(),1);sim.pointerCancelled();assert.equal(sim.state.enemies.includes(enemy),true);assert.equal(enemy.status,identity.status);assert.equal(enemy.hp,identity.hp);assert.equal(enemy.attackCooldown,identity.cooldown);
sim.setPointerWorld(enemy.x,enemy.y);sim.secondaryPress();sim.setPointerWorld(water.x,water.y);sim.secondaryRelease();assert.deepEqual({x:enemy.x,y:enemy.y},{x:identity.x,y:identity.y},"enemy dropped into water");
sim.setPointerWorld(enemy.x,enemy.y);sim.secondaryPress();sim.windowBlurred();assert.equal(sim.state.enemies.includes(enemy),true);assert.deepEqual({x:enemy.x,y:enemy.y},{x:identity.x,y:identity.y});
sim.spawnEnemy("brute");const heavy=sim.state.enemies.at(-1);heavy.x=enemy.x+80;heavy.y=enemy.y;sim.setPointerWorld(heavy.x,heavy.y);sim.secondaryPress();assert.equal(sim.heldEnemy(),null);sim.secondaryRelease();
sim.state.enemies.splice(sim.state.enemies.indexOf(heavy),1);   // the fixed heavy would otherwise maul the capture-yard fixtures below

// Capture Yard: a completed yard converts a dropped light enemy into a linked ally with its current
// HP and no hostile references; occupancy is derived per yard, capacity is three LIVING units, an
// incomplete or full yard restores the exact pickup origin, and a death reopens exactly one slot.
sim.DBG.freeCosts=true;place("bpCaptureYard");const yardA=sim.buildings.find(building=>building.type==="captureYard");assert.equal(yardA.complete,true);
sim.DBG.freeCosts=false;const siteAnchor=place("bpCaptureYard");const yardSite=sim.buildings.at(-1);assert.equal(yardSite.type,"captureYard");assert.equal(!!yardSite.complete,false);
const enemyOrigin={x:enemy.x,y:enemy.y};
sim.setPointerWorld(enemy.x,enemy.y);sim.secondaryPress();assert.equal(sim.heldEnemy(),enemy);sim.setPointerWorld(siteAnchor.x,siteAnchor.y);sim.secondaryRelease();
assert.equal(sim.state.enemies.includes(enemy),true,"incomplete yard consumed the enemy");assert.deepEqual({x:enemy.x,y:enemy.y},enemyOrigin,"incomplete-yard rejection did not restore the pickup origin");
assert.equal(sim.livingActiveWaveEnemies(),1,"scheduled raider must still gate dawn before capture");
sim.setPointerWorld(enemy.x,enemy.y);sim.secondaryPress();sim.setPointerWorld(yardA.x,yardA.y);sim.secondaryRelease();
assert.equal(sim.controlledEnemies.includes(enemy),true);assert.equal(sim.state.enemies.includes(enemy),false);assert.equal(enemy.sourceYard,yardA);
assert.equal(enemy.waveNightNumber,undefined,"capture must leave hostile wave accounting");assert.equal(sim.livingActiveWaveEnemies(),0);
assert.equal(enemy.status.slow,null,"hostile status survived conversion");assert.equal(sim.captureYardOccupancy(yardA),1);
const capture=(type,yard)=>{sim.spawnEnemy(type);const target=sim.state.enemies.at(-1);target.x=yard.x+150;target.y=yard.y;sim.setPointerWorld(target.x,target.y);sim.secondaryPress();assert.equal(sim.heldEnemy(),target);sim.setPointerWorld(yard.x,yard.y);sim.secondaryRelease();return target;};
const allyArcher=capture("archer",yardA);assert.equal(sim.captureYardOccupancy(yardA),2);
const allyRaider=capture("raider",yardA);assert.equal(sim.captureYardOccupancy(yardA),3);
sim.spawnEnemy("raider");const fourth=sim.state.enemies.at(-1);fourth.x=yardA.x+150;fourth.y=yardA.y;
sim.setPointerWorld(fourth.x,fourth.y);sim.secondaryPress();sim.setPointerWorld(yardA.x,yardA.y);sim.secondaryRelease();
assert.equal(sim.state.enemies.includes(fourth),true,"a full yard accepted a fourth capture");assert.deepEqual({x:fourth.x,y:fourth.y},{x:yardA.x+150,y:yardA.y},"full-yard rejection did not restore the pickup origin");assert.equal(sim.captureYardOccupancy(yardA),3);
sim.DBG.freeCosts=true;place("bpCaptureYard");const yardB=sim.buildings.filter(building=>building.type==="captureYard"&&building.complete).at(-1);assert.notEqual(yardB,yardA);
sim.setPointerWorld(fourth.x,fourth.y);sim.secondaryPress();sim.setPointerWorld(yardB.x,yardB.y);sim.secondaryRelease();
assert.equal(fourth.sourceYard,yardB,"a second yard must accept captures independently of a full one");assert.equal(sim.captureYardOccupancy(yardB),1);assert.equal(sim.captureYardOccupancy(yardA),3);
allyRaider.x=yardA.x-150;allyRaider.y=yardA.y;   // off the shared muster point, so the brute's nearest-target pick is unambiguous
sim.spawnEnemy("brute");const killer=sim.state.enemies.at(-1);killer.x=allyRaider.x+20;killer.y=allyRaider.y;killer.attackCooldown=0;
sim.update(.01);
assert.equal(sim.controlledEnemies.includes(allyRaider),false,"hostile brute could not kill the controlled raider");assert.equal(sim.captureYardOccupancy(yardA),2,"ally death did not reopen its yard slot");
const replacement=capture("raider",yardA);assert.equal(sim.captureYardOccupancy(yardA),3,"reopened slot rejected a replacement capture");assert.equal(replacement.sourceYard,yardA);
// Controlled archers fight with their authored ranged kit; controlled healers heal ALLIES only.
sim.state.enemies.length=0;
sim.spawnEnemy("raider");const mark=sim.state.enemies.at(-1);mark.x=allyArcher.x+100;mark.y=allyArcher.y;const markHp=mark.hp;
for(const unit of sim.controlledEnemies)unit.attackCooldown=0;
sim.update(.01);
assert.ok(mark.hp<markHp,"controlled archer did not attack a hostile inside the guard radius");
sim.state.enemies.length=0;
const allyHealer=capture("healer",yardB);fourth.hp=1;allyHealer.x=fourth.x+30;allyHealer.y=fourth.y;allyHealer.healCooldown=0;
sim.update(.01);
assert.ok(fourth.hp>1,"controlled healer did not heal an injured allied unit");

Math.random=originalRandom;sim.validateSimulationInvariants();console.log("card mechanics ok");
