#!/usr/bin/env node
// Deterministic, DOM-free repository validation and sustained simulation stress.

import assert from "node:assert/strict";
import {execFileSync} from "node:child_process";
import {readFileSync,readdirSync,statSync} from "node:fs";
import {join,relative,resolve} from "node:path";
import {fileURLToPath,pathToFileURL} from "node:url";

const root=resolve(fileURLToPath(new URL("..",import.meta.url)));
function filesUnder(dir){
  const output=[];
  for(const name of readdirSync(dir).sort()){
    const path=join(dir,name),stat=statSync(path);
    if(stat.isDirectory()){if(name!==".git"&&name!==".pi")output.push(...filesUnder(path));}
    else output.push(path);
  }
  return output;
}
const jsFiles=filesUnder(root).filter(path=>/\.(?:js|mjs)$/.test(path));
for(const path of jsFiles)execFileSync(process.execPath,["--check",path],{stdio:"pipe"});

let randomState=0x5eed1234;
const originalRandom=Math.random;
Math.random=()=>((randomState=Math.imul(randomState,1664525)+1013904223>>>0)/0x100000000);
let sim,data,showcase;
try{
  [sim,data,showcase]=await Promise.all([
    import(pathToFileURL(join(root,"src/game/simulation.js"))),
    import(pathToFileURL(join(root,"src/game/data.js"))),
    import(pathToFileURL(join(root,"src/game/showcase-data.js")))
  ]);

  assert.equal(sim.state.runMode,"normal");
  assert.equal(sim.damageDummies.length,0);
  assert.equal(sim.showcaseProps.length,0);
  sim.initializeRunMode("normal");
  assert.equal(sim.initializeRunMode("normal"),undefined);
  assert.throws(()=>sim.initializeRunMode("invalid"),/invalid run mode/);
  sim.spawnEnemy("north","raider");const taggedEnemy=sim.state.enemies[0];
  taggedEnemy.combatKind="invalid";assert.throws(()=>sim.validateSimulationInvariants(),/unknown combat kind/);taggedEnemy.combatKind="enemy";
  taggedEnemy.type="invalid";assert.throws(()=>sim.validateSimulationInvariants(),/unknown enemy type/);taggedEnemy.type="raider";
  const invalidDrop={kind:"invalid",x:100,y:100,groundY:100,vx:0,vy:0,ground:true,target:null,t:0,spin:0,ttl:null};sim.resourceDrops.push(invalidDrop);assert.throws(()=>sim.validateSimulationInvariants(),/unknown resource drop kind/);sim.resourceDrops.pop();
  sim.state.runMode="invalid";assert.throws(()=>sim.update(1/60),/invalid run mode/);sim.state.runMode="normal";
  sim.DBG.freeCosts=true;let houseSite=null;for(let y=64;y<data.H-64&&!houseSite;y+=data.CELL)for(let x=64;x<data.W-64;x+=data.CELL)if(sim.canPlace(x,y,"house")){houseSite={x,y};break;}assert.ok(houseSite);sim.setPointerWorld(houseSite.x,houseSite.y);sim.toggleBuildMode("house");sim.primaryPress();sim.primaryRelease();sim.DBG.instantWorkers=true;sim.update(1/60);const worker=sim.state.workers[0],workerOrigin={x:worker.x,y:worker.y};sim.setPointerWorld(worker.x,worker.y);sim.secondaryPress();assert.equal(sim.heldWorker(),worker);sim.pointerCancelled();assert.equal(worker.x,workerOrigin.x);assert.equal(worker.y,workerOrigin.y);assert.equal(sim.state.workers.includes(worker),true);sim.DBG.freeCosts=sim.DBG.instantWorkers=false;

  // Focused deterministic regressions run in a clean process so fixtures cannot leak into stress.
  const featureResult=JSON.parse(execFileSync(process.execPath,["--input-type=module","-"],{
    cwd:root,encoding:"utf8",input:`
      import assert from "node:assert/strict";
      import * as sim from "./src/game/simulation.js";
      import * as data from "./src/game/data.js";
      let seed=0x51a7;const old=Math.random;Math.random=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/0x100000000);
      const counts=()=>({wood:0,stone:0,dust:0,coin:0,diamond:0});
      const building=(type,x,y,complete=true,cost={wood:1,stone:0})=>({type,x,y,complete,cost,delivered:{wood:0,stone:0},storage:counts(),upgrades:{},activeUpgrade:null,tower:null,hazard:null,pulse:0,starved:false});
      const worker=(job,target,x,y)=>({x,y,postX:x,postY:y+20,spawnSource:null,job,jobTarget:target,homePost:null,taskTarget:null,selfSupply:null,returning:false,starved:false,carried:counts(),hp:data.WORKER_HP,attackCooldown:0,hitCooldown:.5,step:0,combatTarget:null,retaliationTarget:null,returnAfterCombat:false,fleeing:false,fleeSafeTime:0,reposting:false});
      const drop=(kind,x,y)=>({kind,x,y,groundY:y,vx:0,vy:0,ground:true,target:null,t:0,spin:0,ttl:null});
      const reset=()=>{sim.buildings.length=sim.resourceDrops.length=sim.state.workers.length=sim.state.enemies.length=sim.trees.length=sim.rocks.length=sim.diamonds.length=0;for(const kind of data.RESOURCE_KINDS)sim.state.stored[kind]=0;sim.state.paused=sim.state.gameOver=false;sim.DBG.groundSourcing=sim.DBG.blueprintRecruiting=sim.DBG.builderSelfSupply=true;sim.DBG.idleSeeksWork=false;sim.DBG.instantWorkers=false;sim.TUNE.builderSourceRadius=300;sim.TUNE.recruitRadius=200;sim.TUNE.fleeHpThreshold=1;};
      const step=(n=1)=>{for(let i=0;i<n;i++)sim.update(1/60);};
      // Recruitment cadence is private; disabling it while time advances makes the next enabled step due.
      const forceRecruitSweep=()=>{sim.DBG.blueprintRecruiting=false;step(31);sim.DBG.blueprintRecruiting=true;step();};
      try{
        sim.initializeRunMode("normal");
        assert.deepEqual(Object.entries(data.BUILDING_TYPES).filter(([,def])=>def.jobSlots).map(([type,def])=>[type,def.jobSlots]),[["lumber",2],["quarry",2],["stockpile",2]]);assert.equal(data.RESOURCE_NODE_JOB_SLOTS,1);assert.equal(data.BLUEPRINT_JOB_SLOTS,2);
        assert.equal(sim.DBG.groundSourcing,true);assert.equal(sim.TUNE.builderSourceRadius,300);
        reset();{const site=building("lumber",100,100,false),store=building("stockpile",110,100);store.storage.wood=3;const loose=drop("wood",104,100),builder=worker("build",site,100,100);sim.buildings.push(site,store);sim.resourceDrops.push(loose);sim.state.workers.push(builder);sim.DBG.groundSourcing=false;step();assert.equal(builder.taskTarget,null);assert.ok(builder.carried.wood>0);assert.equal(loose.claimedBy,undefined);}
        reset();{const site=building("lumber",100,100,false),store=building("stockpile",110,100);store.storage.wood=3;const loose=drop("wood",130,100),builder=worker("build",site,100,100);sim.buildings.push(site,store);sim.resourceDrops.push(loose);sim.state.workers.push(builder);sim.DBG.groundSourcing=true;step();assert.equal(builder.taskTarget,loose);assert.equal(loose.claimedBy,builder);assert.equal(store.storage.wood,3);sim.DBG.groundSourcing=false;sim.TUNE.builderSourceRadius=60;step();assert.equal(builder.taskTarget,loose);}
        reset();{const site=building("lumber",100,100,false),store=building("stockpile",110,100);store.storage.wood=1;const builder=worker("build",site,100,100);sim.buildings.push(site,store);sim.state.workers.push(builder);sim.DBG.groundSourcing=true;step();assert.equal(builder.carried.wood,1);}
        reset();{const site=building("lumber",100,100,false),builder=worker("build",site,100,100);sim.buildings.push(site);sim.state.workers.push(builder);step();assert.equal(builder.starved,true);}
        reset();{const site=building("lumber",100,100,false),tree={x:180,y:100,hp:3,max:3,stump:0,shake:0},builder=worker("build",site,100,100),savedHome={job:"guard",jobTarget:null,postX:40,postY:50};builder.homePost=savedHome;sim.buildings.push(site);sim.trees.push(tree);sim.state.workers.push(builder);step();assert.equal(builder.job,"build");assert.equal(builder.jobTarget,site);assert.equal(builder.homePost,savedHome);assert.equal(builder.selfSupply.node,tree);step(600);assert.equal(site.complete,true);assert.equal(site.delivered.wood,1);assert.equal(builder.homePost,null);assert.equal(builder.selfSupply,null);assert.equal(sim.resourceDrops.some(item=>item.claimedBy===builder),false);}
        reset();{const site=building("tower",100,100,false,{wood:1,stone:1}),tree={x:190,y:100,hp:3,max:3,stump:0,shake:0},rock={x:130,y:100,hp:3,max:3,depleted:0,shake:0},builder=worker("build",site,100,100);sim.buildings.push(site);sim.trees.push(tree);sim.rocks.push(rock);sim.state.workers.push(builder);step();assert.deepEqual(builder.selfSupply,{kind:"stone",node:rock},"nearest needed node must win across kinds");}
        reset();{const site=building("tower",100,100,false,{wood:1,stone:1}),tree={x:130,y:100,hp:3,max:3,stump:0,shake:0},rock={x:190,y:100,hp:3,max:3,depleted:0,shake:0},builder=worker("build",site,100,100);sim.buildings.push(site);sim.trees.push(tree);sim.rocks.push(rock);sim.state.workers.push(builder);step();assert.deepEqual(builder.selfSupply,{kind:"wood",node:tree},"nearest needed node must win across kinds");}
        reset();{const site=building("tower",100,100,false,{wood:2,stone:0}),tree={x:170,y:100,hp:6,max:6,stump:0,shake:0},a=worker("build",site,100,100),b=worker("build",site,102,100);sim.buildings.push(site);sim.trees.push(tree);sim.state.workers.push(a,b);step();assert.ok(a.selfSupply||b.selfSupply);assert.equal([a,b].filter(item=>item.selfSupply).length,1,"node/self-supply reservation duplicated");step(700);assert.equal(site.delivered.wood,site.cost.wood);assert.equal(site.complete,true,"builders must reselect without over-delivery");}
        reset();{const site=building("lumber",100,100,false),tree={x:180,y:100,hp:3,max:3,stump:0,shake:0},builder=worker("build",site,100,100);sim.buildings.push(site);sim.trees.push(tree);sim.state.workers.push(builder);step(90);assert.ok(builder.selfSupply);sim.setPointerWorld(builder.x,builder.y);sim.secondaryPress();assert.equal(builder.selfSupply,null);assert.equal(sim.resourceDrops.some(item=>item.claimedBy===builder),false);sim.pointerCancelled();}
        reset();{const site=building("lumber",100,100,false),tree={x:180,y:100,hp:3,max:3,stump:0,shake:0},builder=worker("build",site,100,100);sim.buildings.push(site);sim.trees.push(tree);sim.state.workers.push(builder);step(90);builder.hp=1;sim.spawnEnemy("north","healer");const danger=sim.state.enemies[0];danger.x=builder.x+5;danger.y=builder.y;step();assert.equal(builder.fleeing,true);assert.equal(builder.selfSupply,null);assert.equal(sim.resourceDrops.some(item=>item.claimedBy===builder),false);assert.equal(builder.job,"build");assert.equal(builder.jobTarget,site);}
        reset();{const site=building("lumber",100,100,false),tree={x:180,y:100,hp:3,max:3,stump:0,shake:0},builder=worker("build",site,100,100);sim.buildings.push(site);sim.trees.push(tree);sim.state.workers.push(builder);sim.DBG.builderSelfSupply=false;step();assert.equal(builder.starved,true);assert.equal(builder.selfSupply,null);assert.equal(builder.x,100);assert.ok(builder.y>100&&builder.y<=builder.postY);}
        reset();{const site=building("lumber",100,100,false),loose=drop("wood",105,100),builder=worker("build",site,100,100);sim.buildings.push(site);sim.resourceDrops.push(loose);sim.state.workers.push(builder);sim.DBG.groundSourcing=true;step();assert.equal(builder.taskTarget,loose);}
        reset();{const site=building("lumber",100,100,false,{wood:2,stone:0}),a=worker("build",site,100,100),b=worker("build",site,101,100),one=drop("wood",104,100),two=drop("wood",106,100);sim.buildings.push(site);sim.resourceDrops.push(one,two);sim.state.workers.push(a,b);sim.DBG.groundSourcing=true;step();assert.ok(a.taskTarget&&b.taskTarget);assert.notEqual(a.taskTarget,b.taskTarget);step(500);assert.ok(site.delivered.wood<=site.cost.wood);assert.equal(site.complete,true);assert.equal(a.job,"staff");assert.equal(a.jobTarget,site);}
        reset();{const site=building("lumber",100,100,false),a=worker("build",site,100,100),b=worker("build",site,101,100),c=worker("build",site,102,100);a.carried.wood=1;sim.buildings.push(site);sim.state.workers.push(a,b,c);step();assert.equal(site.complete,true);assert.equal(sim.workerOccupancyStatus(site).assigned,2);assert.deepEqual([a,b,c].map(item=>item.job).sort(),["guard","staff","staff"]);assert.equal([a,b,c].find(item=>item.job==="guard").jobTarget,null);}
        reset();{const house=building("house",500,500),near=building("lumber",560,500),far=building("stockpile",700,500);house.spawnTimer=0;sim.buildings.push(house,near,far);sim.DBG.instantWorkers=true;step();const born=sim.state.workers[0];assert.equal(born.jobTarget,near);let status=sim.durablePostStatus(near);assert.equal(status.assigned,1);assert.equal(status.arrived,0);assert.equal(sim.vacantDurablePosts().includes(near),true);step(600);status=sim.durablePostStatus(near);assert.equal(status.arrived,2);}
        reset();{sim.trees.length=sim.rocks.length=sim.diamonds.length=0;const first=building("lumber",300,300),second=building("quarry",600,300),staff=worker("staff",first,first.x,first.y+16);staff.postX=first.x;staff.postY=first.y+16;sim.buildings.push(first,second);sim.state.workers.push(staff);step();assert.equal(sim.durablePostStatus(first).arrived,1);sim.setPointerWorld(staff.x,staff.y);sim.secondaryPress();sim.setPointerWorld(second.x,second.y);sim.secondaryRelease();assert.equal(staff.jobTarget,second);assert.equal(sim.durablePostStatus(first).assigned,0);assert.equal(sim.durablePostStatus(second).arrived,0);step();assert.equal(sim.durablePostStatus(second).arrived,0);step(600);assert.equal(sim.durablePostStatus(second).arrived,1);}
        reset();{const site=building("lumber",300,300,false),builder=worker("build",site,site.x,site.y);builder.carried.wood=1;sim.buildings.push(site);sim.state.workers.push(builder);step();assert.equal(site.complete,true);assert.equal(builder.jobTarget,site);assert.equal(sim.durablePostStatus(site).arrived,0);step(20);assert.equal(sim.durablePostStatus(site).arrived,1);}
        reset();{const house=building("house",500,500);house.spawnTimer=0;sim.buildings.push(house);sim.DBG.instantWorkers=true;step();const born=sim.state.workers[0];assert.equal(born.job,"guard");assert.equal(born.jobTarget,null);assert.equal(born.postX,house.x);assert.equal(born.postY,house.y+23);}
        reset();{const house=building("house",500,500),camp=building("lumber",550,500);house.spawnTimer=0;const staff=worker("staff",camp,camp.x,camp.y+16);staff.spawnSource=house;staff.postX=camp.x;staff.postY=camp.y+16;sim.buildings.push(house,camp);sim.state.workers.push(staff);sim.setPointerWorld(staff.x,staff.y);sim.secondaryPress();assert.equal(sim.heldWorker(),staff);assert.equal(sim.durablePostStatus(camp).assigned,1);sim.DBG.instantWorkers=true;step();assert.equal(sim.durablePostStatus(camp).assigned,2);sim.pointerCancelled();}
        reset();{sim.trees.length=sim.rocks.length=sim.diamonds.length=0;const tree={x:200,y:200,hp:3,max:3,stump:0};sim.trees.push(tree);const first=worker("harvest",{node:tree,kind:"wood"},200,200),held=worker("guard",null,210,200);sim.state.workers.push(first,held);assert.deepEqual(sim.workerOccupancyStatus(tree),{target:tree,assigned:1,capacity:1});assert.equal(sim.workerAssignmentAt(held,tree.x,tree.y),null);sim.setPointerWorld(first.x,first.y);sim.secondaryPress();assert.equal(sim.workerOccupancyStatus(tree).assigned,1);assert.ok(sim.workerAssignmentAt(first,tree.x,tree.y));sim.pointerCancelled();}
        reset();{sim.trees.length=sim.rocks.length=sim.diamonds.length=0;const one={x:200,y:200,hp:3,max:3,stump:0},two={x:240,y:200,hp:3,max:3,stump:0};sim.trees.push(one,two);const a=worker("harvest",{node:one,kind:"wood"},200,200),b=worker("harvest",{node:null,kind:"wood"},220,200);sim.state.workers.push(a,b);step();assert.equal(b.jobTarget.node,two);assert.equal(sim.workerOccupancyStatus(one).assigned,1);assert.equal(sim.workerOccupancyStatus(two).assigned,1);}
        reset();{const camp=building("lumber",300,300),a=worker("staff",camp,300,316),b=worker("staff",camp,301,316),held=worker("guard",null,310,300);sim.buildings.push(camp);sim.state.workers.push(a,b,held);assert.equal(sim.workerOccupancyStatus(camp).assigned,2);assert.equal(sim.workerAssignmentAt(held,camp.x,camp.y),null);sim.setPointerWorld(a.x,a.y);sim.secondaryPress();assert.equal(sim.workerOccupancyStatus(camp).assigned,2);assert.ok(sim.workerAssignmentAt(a,camp.x,camp.y));sim.pointerCancelled();}
        reset();{const site=building("tower",300,300,false),a=worker("build",site,300,320),b=worker("build",site,301,320),held=worker("guard",null,310,300);sim.buildings.push(site);sim.state.workers.push(a,b,held);assert.deepEqual(sim.workerOccupancyStatus(site),{target:site,assigned:2,capacity:2});assert.equal(sim.workerAssignmentAt(held,site.x,site.y),null);sim.setPointerWorld(a.x,a.y);sim.secondaryPress();assert.equal(sim.workerOccupancyStatus(site).assigned,2);assert.ok(sim.workerAssignmentAt(a,site.x,site.y));sim.pointerCancelled();}
        reset();{sim.trees.length=sim.rocks.length=sim.diamonds.length=0;const tree={x:200,y:200,hp:3,max:3,stump:0},camp=building("lumber",232,200),far=building("quarry",264,200);sim.trees.push(tree);sim.buildings.push(far,camp);assert.equal(sim.workerOccupancyAt(camp.x,camp.y).target,camp);assert.equal(sim.workerOccupancyAt(far.x,far.y).target,far);tree.stump=1;sim.buildings.length=0;assert.equal(sim.workerOccupancyAt(tree.x,tree.y),null);}
        assert.equal(sim.DBG.blueprintRecruiting,true);assert.equal(sim.TUNE.recruitRadius,200);
        reset();{const site=building("tower",300,300,false,{wood:99,stone:0}),a=worker("guard",null,300,316),b=worker("guard",null,340,300),replacement=worker("guard",null,350,300),far=worker("guard",null,561,300);a.carried.dust=1;sim.buildings.push(site);sim.state.workers.push(far,replacement,b,a);sim.DBG.blueprintRecruiting=false;step(31);a.x=300;a.y=316;const before={x:a.x,y:a.y,carried:{...a.carried}};sim.DBG.blueprintRecruiting=true;step();assert.deepEqual([a,b].map(item=>item.job),["build","build"]);assert.ok(a.homePost&&b.homePost);assert.deepEqual({x:a.x,y:a.y,carried:a.carried},before);assert.equal(far.job,"guard");assert.equal(sim.workerOccupancyStatus(site).assigned,2);a.hp=2;sim.spawnEnemy("north","raider");const killer=sim.state.enemies[0];killer.x=a.x;killer.y=a.y;step();assert.equal(sim.state.workers.includes(a),false,"production enemy hit did not kill builder");sim.state.enemies.length=0;step(28);assert.equal(replacement.job,"guard","recruited before cadence");const elapsedBeforePause=sim.state.clock.elapsed;sim.togglePause();step(60);assert.equal(sim.state.clock.elapsed,elapsedBeforePause);assert.equal(replacement.job,"guard");sim.togglePause();step(2);assert.equal(replacement.job,"build","not recruited once cadence elapsed");}
        reset();{const first=building("tower",300,300,false,{wood:99,stone:0}),second=building("tower",500,300,false,{wood:99,stone:0}),a=worker("guard",null,310,300),b=worker("guard",null,320,300),c=worker("guard",null,490,300);sim.buildings.push(first,second);sim.state.workers.push(c,b,a);forceRecruitSweep();assert.equal(sim.workerOccupancyStatus(first).assigned,2);assert.equal(sim.workerOccupancyStatus(second).assigned,1);assert.equal(c.jobTarget,second);}
        reset();{const site=building("tower",300,300,false,{wood:99,stone:0}),manual=worker("build",site,300,320),near=worker("guard",null,310,300),far=worker("guard",null,330,300);sim.buildings.push(site);sim.state.workers.push(manual,far,near);forceRecruitSweep();assert.equal(near.job,"build");assert.equal(far.job,"guard");assert.equal(sim.workerOccupancyStatus(site).assigned,2);}
        reset();{const site=building("lumber",300,300,false),manual=worker("build",site,300,300),loan=worker("guard",null,310,300);loan.postX=100;loan.postY=120;sim.buildings.push(site);sim.state.workers.push(manual,loan);assert.equal(sim.workerIsLoaned(manual),false);forceRecruitSweep();assert.equal(sim.workerIsLoaned(loan),true);manual.carried.wood=1;step(20);assert.equal(site.complete,true);assert.equal(manual.job,"staff");assert.equal(manual.jobTarget,site);assert.equal(loan.job,"staff");assert.equal(loan.jobTarget,site);assert.equal(loan.homePost,null);assert.equal(sim.workerIsLoaned(loan),false);}
        reset();{const house=building("house",500,500),site=building("lumber",300,300,false),resident=worker("staff",site,300,316),loan=worker("guard",null,310,300),finisher=worker("build",site,300,300);house.spawnTimer=data.WORKER_SPAWN_TIME;resident.postX=site.x;resident.postY=site.y+16;loan.postX=80;loan.postY=90;sim.buildings.push(house,site);sim.state.workers.push(resident,loan,finisher);sim.DBG.blueprintRecruiting=false;step(31);sim.DBG.blueprintRecruiting=true;step();assert.equal(loan.job,"build");assert.equal(sim.state.workers.indexOf(loan)<sim.state.workers.indexOf(finisher),true);finisher.carried.wood=1;house.spawnTimer=2/60;step();assert.equal(site.complete,true);assert.equal(loan.job,"staff");assert.equal(loan.jobTarget,site);assert.equal(finisher.job,"guard");assert.equal(finisher.jobTarget,null);assert.equal(sim.durablePostStatus(site).assigned,2);const beforeSpawn=sim.state.workers.length;step();assert.equal(sim.state.workers.length,beforeSpawn+1);const born=sim.state.workers.at(-1);assert.notEqual(born.jobTarget,site);assert.equal(sim.durablePostStatus(site).assigned,2);}
        reset();{const site=building("tower",300,300,false,{wood:1,stone:0}),a=worker("guard",null,310,300),b=worker("guard",null,320,300);a.postX=80;b.postX=90;sim.buildings.push(site);sim.state.workers.push(a,b);forceRecruitSweep();a.carried.wood=1;step(20);assert.equal(site.complete,true);assert.deepEqual([a.job,b.job],["guard","guard"]);assert.deepEqual([a.postX,b.postX],[80,90]);}
        reset();{const site=building("lumber",300,300,false,{wood:99,stone:0}),resident=worker("staff",site,300,316),a=worker("guard",null,310,300),b=worker("guard",null,320,300);a.postX=80;b.postX=90;sim.buildings.push(site);sim.state.workers.push(resident,a,b);forceRecruitSweep();site.complete=true;step();assert.equal([a,b].filter(item=>item.job==="staff"&&item.jobTarget===site).length,1);assert.equal([a,b].filter(item=>item.job==="guard"&&item.homePost===null).length,1);}
        reset();{const site=building("lumber",300,300,false,{wood:99,stone:0}),one=worker("staff",site,300,316),two=worker("staff",site,301,316),a=worker("guard",null,310,300),b=worker("guard",null,320,300);a.postX=80;b.postX=90;sim.buildings.push(site);sim.state.workers.push(one,two,a,b);forceRecruitSweep();site.complete=true;step();assert.deepEqual([a.job,b.job],["guard","guard"]);assert.deepEqual([a.postX,b.postX],[80,90]);}
        reset();{const site=building("tower",300,300,false,{wood:99,stone:0}),a=worker("guard",null,310,300),b=worker("guard",null,320,300),replacement=worker("guard",null,330,300);sim.buildings.push(site);sim.state.workers.push(a,b,replacement);forceRecruitSweep();assert.equal(replacement.job,"guard");sim.state.workers.splice(sim.state.workers.indexOf(a),1);step(31);assert.equal(replacement.job,"build");assert.equal(sim.workerOccupancyStatus(site).assigned,2);}
        reset();{const site=building("tower",300,300,false,{wood:99,stone:0}),loan=worker("guard",null,310,300),builder=worker("guard",null,320,300),replacement=worker("guard",null,330,300);sim.buildings.push(site);sim.state.workers.push(loan,builder,replacement);forceRecruitSweep();assert.equal(replacement.job,"guard");sim.setPointerWorld(loan.x,loan.y);sim.secondaryPress();sim.setPointerWorld(700,700);sim.secondaryRelease();step(31);assert.equal(replacement.job,"build");assert.equal(sim.workerOccupancyStatus(site).assigned,2);}
        reset();{const site=building("tower",300,300,false,{wood:99,stone:0}),combat=worker("guard",null,310,300),retaliating=worker("guard",null,320,300),returning=worker("guard",null,330,300),clean=worker("guard",null,340,300);clean.x=300;clean.y=320;clean.postX=300;clean.postY=320;sim.buildings.push(site);sim.state.workers.push(combat,retaliating,returning,clean);sim.DBG.blueprintRecruiting=false;step(31);combat.combatTarget={};retaliating.retaliationTarget={};returning.returnAfterCombat=true;sim.DBG.blueprintRecruiting=true;step();assert.equal(clean.job,"build");assert.equal(combat.job,"guard");assert.equal(retaliating.job,"guard");assert.equal(returning.job,"guard");}
        reset();{const site=building("tower",300,300,false,{wood:99,stone:0}),loan=worker("guard",null,310,300),other=worker("guard",null,320,300);sim.buildings.push(site);sim.state.workers.push(loan,other);sim.DBG.blueprintRecruiting=false;step(31);assert.deepEqual([loan.job,other.job],["guard","guard"]);sim.DBG.blueprintRecruiting=true;step();assert.equal(loan.job,"build");sim.DBG.blueprintRecruiting=false;site.complete=true;step();assert.equal(loan.job,"guard");assert.equal(loan.homePost,null);}
        reset();{const home=building("tower",100,100),site=building("tower",300,300,false,{wood:99,stone:0}),loan=worker("guard",home,310,300);loan.postX=home.x;loan.postY=home.y;sim.buildings.push(home,site);sim.state.workers.push(loan);forceRecruitSweep();assert.equal(loan.job,"build");sim.buildings.splice(sim.buildings.indexOf(home),1);site.complete=true;step();assert.equal(loan.job,"guard");assert.equal(loan.jobTarget,null);assert.notDeepEqual([loan.postX,loan.postY],[home.x,home.y]);}
        reset();{const tower=building("tower",120,100),site=building("lumber",300,300,false,{wood:99,stone:0}),loan=worker("build",site,200,100),claimed=drop("wood",202,100);tower.tower={variant:"basic",cooldown:0,flash:0,hitFlash:0,hp:10,maxHp:10};loan.hp=1;loan.carried.dust=1;const savedHome={job:"guard",jobTarget:null,postX:450,postY:450};loan.homePost=savedHome;loan.taskTarget=claimed;loan.retaliationTarget={x:205,y:100};claimed.claimedBy=loan;sim.buildings.push(tower,site);sim.resourceDrops.push(claimed);sim.state.workers.push(loan);sim.spawnEnemy("north","healer");const danger=sim.state.enemies[0];danger.x=210;danger.y=100;const prior={job:loan.job,jobTarget:loan.jobTarget,homePost:loan.homePost,carried:{...loan.carried}};step();assert.equal(loan.fleeing,true);assert.equal(loan.taskTarget,null);assert.equal(claimed.claimedBy,undefined);assert.equal(loan.job,prior.job);assert.equal(loan.jobTarget,prior.jobTarget);assert.equal(loan.homePost,prior.homePost);assert.deepEqual(loan.homePost,savedHome);assert.deepEqual(loan.carried,prior.carried);assert.equal(loan.combatTarget,null);assert.equal(loan.retaliationTarget,null);const fledX=loan.x;step(10);assert.ok(loan.x<fledX);danger.x=700;danger.y=700;step(179);assert.equal(loan.fleeing,true);danger.x=loan.x+data.WORKER_LEASH+5;danger.y=loan.y;step();assert.equal(loan.fleeing,true,"danger inside recovery radius must reset safe time without causing fight/flee oscillation");assert.equal(loan.combatTarget,null);danger.x=700;danger.y=700;step(179);assert.equal(loan.fleeing,true);step(2);assert.equal(loan.fleeing,false);assert.equal(loan.job,prior.job);assert.equal(loan.jobTarget,prior.jobTarget);assert.equal(loan.homePost,prior.homePost);assert.deepEqual(loan.carried,prior.carried);assert.equal(loan.hp,1);}
        reset();{const low=worker("guard",null,200,100);low.hp=1;sim.state.workers.push(low);sim.spawnEnemy("north","healer");const danger=sim.state.enemies[0];danger.x=205;danger.y=100;step();assert.equal(low.fleeing,true);sim.setPointerWorld(low.x,low.y);sim.secondaryPress();assert.equal(sim.heldWorker(),low);sim.setPointerWorld(500,500);sim.secondaryRelease();assert.equal(low.fleeing,false);assert.equal(low.fleeSafeTime,0);assert.deepEqual([low.x,low.y],[500,500]);}
        reset();{const healthy=worker("guard",null,200,100);healthy.hp=sim.TUNE.fleeHpThreshold+1;healthy.attackCooldown=0;sim.state.workers.push(healthy);sim.spawnEnemy("north","healer");const enemy=sim.state.enemies[0];enemy.x=healthy.x;enemy.y=healthy.y;const hpBefore=enemy.hp;step();assert.equal(healthy.fleeing,false);assert.equal(healthy.combatTarget,enemy);assert.equal(enemy.hp,hpBefore-data.WORKER_DAMAGE);assert.equal(healthy.attackCooldown,data.WORKER_ATTACK_RATE);}
        reset();{const house=building("house",100,100),camp=building("lumber",295,100),idle=worker("guard",null,100,123);idle.spawnSource=house;idle.postX=100;idle.postY=123;house.spawnTimer=data.WORKER_SPAWN_TIME;sim.buildings.push(house,camp);sim.state.workers.push(idle);sim.DBG.blueprintRecruiting=false;sim.DBG.idleSeeksWork=true;step(31);assert.equal(idle.job,"staff");assert.equal(idle.jobTarget,camp);assert.equal(idle.homePost,null);assert.equal(idle.reposting,true);assert.equal(idle.spawnSource,house);}
        reset();{const house=building("house",100,100),camp=building("lumber",300,100),manual=worker("guard",null,110,123);manual.spawnSource=house;manual.postX=110;manual.postY=123;sim.buildings.push(house,camp);sim.state.workers.push(manual);sim.DBG.blueprintRecruiting=false;sim.DBG.idleSeeksWork=true;step(31);assert.equal(manual.job,"guard");sim.DBG.idleSeeksWork=false;manual.postX=100;step(31);assert.equal(manual.job,"guard");}
        reset();{const site=building("tower",200,100,false,{wood:1,stone:0}),guard=worker("guard",null,100,100),loose=drop("wood",105,100);guard.postX=200;guard.postY=100;guard.returnAfterCombat=true;sim.DBG.idleSeeksWork=true;sim.buildings.push(site);sim.resourceDrops.push(loose);sim.state.workers.push(guard);sim.DBG.blueprintRecruiting=false;step();assert.equal(guard.carried.wood,1);assert.equal(sim.resourceDrops.includes(loose),false);step(180);assert.equal(site.complete,true);assert.equal(site.delivered.wood,1);assert.equal(guard.carried.wood,0);}
        reset();{const site=building("tower",700,700,false,{wood:99,stone:0}),owner=worker("build",site,700,700),a=worker("guard",null,100,100),b=worker("guard",null,100,101),claimed=drop("wood",105,100);owner.taskTarget=claimed;claimed.claimedBy=owner;a.postX=b.postX=200;a.postY=b.postY=100;a.returnAfterCombat=b.returnAfterCombat=true;sim.buildings.push(site);sim.state.workers.push(owner,a,b);sim.resourceDrops.push(claimed);sim.DBG.idleSeeksWork=true;sim.DBG.blueprintRecruiting=false;step();assert.equal(claimed.claimedBy,owner);assert.equal(sim.resourceDrops.includes(claimed),true);assert.equal(a.carried.wood+b.carried.wood,0);}
        reset();{const a=worker("guard",null,100,100),b=worker("guard",null,100,101),loose=drop("wood",105,100);a.postX=b.postX=200;a.postY=b.postY=100;a.returnAfterCombat=b.returnAfterCombat=true;sim.state.workers.push(a,b);sim.resourceDrops.push(loose);sim.DBG.idleSeeksWork=true;sim.DBG.blueprintRecruiting=false;step();assert.equal(a.carried.wood+b.carried.wood,1);assert.equal(sim.resourceDrops.includes(loose),false);}
        reset();{const site=building("tower",200,100,false,{wood:1,stone:0}),builder=worker("build",site,700,700),guard=worker("guard",null,200,100),loose=drop("wood",205,100);builder.carried.wood=1;guard.postX=200;guard.postY=100;guard.returnAfterCombat=true;sim.buildings.push(site);sim.state.workers.push(builder,guard);sim.resourceDrops.push(loose);sim.DBG.idleSeeksWork=true;sim.DBG.groundSourcing=false;sim.DBG.blueprintRecruiting=false;step();assert.equal(site.delivered.wood,0,"guard must respect the builder's in-flight reservation");assert.equal(guard.carried.wood,0);assert.equal(site.complete,false);assert.equal(sim.resourceDrops.includes(loose),false);const fallback=sim.resourceDrops.find(item=>item.kind==="wood");assert.ok(fallback);assert.equal(fallback.target,null);assert.equal(fallback.claimedBy,undefined);step(120);assert.equal(fallback.ground,true);assert.equal(fallback.target,null);assert.equal(fallback.claimedBy,undefined);}
        console.log(JSON.stringify({checks:55}));
      }finally{Math.random=old;}
    `
  }).trim());
  const html=readFileSync(join(root,"index.html"),"utf8"),overlay=readFileSync(join(root,"src/render/overlay.js"),"utf8"),debuggerSource=readFileSync(join(root,"src/debug/view-debugger.js"),"utf8");
  assert.match(html,/id="vGroundSourcing" checked/);assert.match(html,/id="vBuilderSelfSupply" checked/);assert.match(html,/id="vBuilderRadius" min="60" max="400" step="10" value="300"/);assert.match(html,/id="vBlueprintRecruiting" checked/);assert.match(html,/id="vIdleSeeksWork" checked/);assert.match(html,/id="vRecruitRadius" min="100" max="500" step="20" value="200"/);assert.ok(debuggerSource.includes('bindV("vBuilderSelfSupply", v => { DBG.builderSelfSupply = v; });'));assert.ok(debuggerSource.includes('bindV("vBlueprintRecruiting", v => { DBG.blueprintRecruiting = v; });'));assert.ok(debuggerSource.includes('bindV("vIdleSeeksWork", v => { DBG.idleSeeksWork = v; });'));assert.ok(debuggerSource.includes('bindV("vRecruitRadius", v => { TUNE.recruitRadius = v; }, v => v + "px")'));assert.ok(overlay.includes("workerOccupancyStatus(target)"));assert.ok(overlay.includes("workerOccupancyAt(state.mouse.x,state.mouse.y)"));assert.ok(overlay.includes("drawWorkerSlots(target,height,status)"));assert.ok(overlay.includes("state.workers.length>0||!!heldWorker()"));assert.match(overlay,/hollow circles are vacancies/);assert.match(overlay,/! vacant/);assert.ok(overlay.includes("const BUILD_JOB_ACCENT=css(PAL.jobBuild)"));assert.ok(overlay.includes("workerIsLoaned(worker)"));assert.equal(overlay.includes("worker.homePost"),false);assert.ok(overlay.includes('hovered?.kind==="building"&&!hovered.object.complete'));assert.ok(overlay.includes('worker.job==="build"&&worker.jobTarget===site'));assert.equal(overlay.match(/if\(state\.runMode!=="normal"\)return/g)?.length,2);

  const normalSteps=12000,dt=1/60;
  sim.DBG.invulnBase=true;
  const elapsedBeforeSpeed=sim.state.clock.elapsed;for(let i=0;i<3;i++)sim.update(dt);assert.ok(Math.abs(sim.state.clock.elapsed-elapsedBeforeSpeed-3*dt)<1e-9);
  const elapsedBeforePause=sim.state.clock.elapsed;sim.togglePause();for(let i=0;i<60;i++)sim.update(dt);assert.equal(sim.state.clock.elapsed,elapsedBeforePause);sim.togglePause();
  sim.pressKey("KeyD");
  for(let i=0;i<normalSteps;i++){if(i===300)sim.releaseKey("KeyD");sim.update(dt);if(i%120===0)sim.validateSimulationInvariants();}
  assert.equal(sim.state.gameOver,false);assert.ok(sim.state.clock.elapsed>=normalSteps*dt);
  sim.validateSimulationInvariants();
  assert.equal(sim.damageDummies.length,0);
  assert.equal(sim.showcaseProps.length,0);

  // Production commands reveal the complete graph; every selected node must already be visible.
  let selected=0;
  while(selected<100){
    const available=sim.skillTreeNodes().filter(node=>node.status==="available");
    if(!available.length)break;
    for(const node of available){assert.equal(sim.selectSkillNode(node.id),true);selected++;}
  }
  const skills=sim.skillTreeNodes();
  assert.equal(skills.every(node=>node.status==="selected"),true);
  assert.equal(selected,skills.length);
  sim.validateSimulationInvariants();

  // A clean module process is required to test showcase because run mode is intentionally immutable.
  const showcaseResult=JSON.parse(execFileSync(process.execPath,["--input-type=module","-"],{
    cwd:root,encoding:"utf8",input:`
      import assert from "node:assert/strict";
      let seed=0x5eed1234;const old=Math.random;Math.random=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/0x100000000);
      try{
        const sim=await import("./src/game/simulation.js");
        const data=await import("./src/game/data.js");
        const authored=await import("./src/game/showcase-data.js");
        sim.initializeRunMode("showcase");
        assert.throws(()=>sim.initializeRunMode("normal"),/already initialized/);
        const expected={buildings:authored.SHOWCASE_FIXTURE_COUNTS.buildings+authored.SHOWCASE_FIXTURE_COUNTS.towers+authored.SHOWCASE_FIXTURE_COUNTS.progress,dummies:authored.SHOWCASE_FIXTURE_COUNTS.dummies,props:authored.SHOWCASE_FIXTURE_COUNTS.props,enemies:authored.SHOWCASE_FIXTURE_COUNTS.enemies,workers:authored.SHOWCASE_FIXTURE_COUNTS.workers};
        const check=()=>{sim.validateSimulationInvariants();assert.equal(sim.buildings.length,expected.buildings);assert.equal(sim.damageDummies.length,expected.dummies);assert.equal(sim.showcaseProps.length,expected.props);assert.equal(sim.state.enemies.length,expected.enemies);assert.equal(sim.state.workers.length,expected.workers);assert.equal(sim.state.enemies.every(e=>e.displayUnit),true);assert.equal(sim.state.workers.every(w=>w.displayUnit),true);};
        check();
        const firstRevision=sim.showcaseLabels().revision;
        for(let i=0;i<20;i++){assert.equal(sim.rebuildShowcase(),true);check();}
        assert.ok(sim.showcaseLabels().revision>firstRevision);
        const prop=sim.showcaseProps[0],origin={x:prop.x,y:prop.y};sim.setPointerWorld(prop.x,prop.y);sim.secondaryPress();assert.equal(sim.heldProp(),prop);sim.setPointerWorld(data.BASE.x,data.BASE.y);sim.secondaryRelease();assert.equal(prop.x,origin.x);assert.equal(prop.y,origin.y);assert.equal(sim.showcaseProps.includes(prop),true);
        const shock=sim.buildings.find(b=>b.type==="tower"&&b.tower.variant==="shock"),shockOrigin={x:shock.x,y:shock.y};sim.setPointerWorld(shock.x,shock.y);sim.secondaryPress();assert.equal(sim.heldBuilding(),shock);sim.rebuildShowcase();assert.equal(sim.state.heldObject,null);assert.equal(shock.x,shockOrigin.x);assert.equal(shock.y,shockOrigin.y);check();
        const dummy=sim.damageDummies[0],secondDummy=sim.damageDummies[1],oldDamage=sim.TUNE.clickDamage;sim.TUNE.clickDamage=100;sim.setPointerWorld(dummy.x,dummy.y);sim.primaryPress();for(let i=0;i<60;i++)sim.update(1/60);sim.primaryRelease();assert.ok(dummy.defeatedTimer>0);
        for(const target of sim.damageDummies)target.defeatedTimer=10;const basic=sim.buildings.find(b=>b.type==="tower"&&b.tower.variant==="basic");basic.tower.cooldown=0;sim.update(1/60);assert.equal(basic.tower.cooldown,0,"tower targeted a regenerating dummy");
        sim.resetDamageDummies();for(const target of sim.damageDummies)if(target!==secondDummy)target.defeatedTimer=10;sim.setPointerWorld(secondDummy.x,secondDummy.y);sim.primaryPress();for(let i=0;i<50;i++)sim.update(1/60);sim.primaryRelease();assert.equal(sim.focusedDummyReadout().id,secondDummy.id);sim.TUNE.clickDamage=oldDamage;sim.resetDamageDummies();assert.equal(dummy.hitCount,0);
        const drop=sim.resourceDrops.find(item=>item.kind==="dust");sim.setPointerWorld(drop.x,drop.y);sim.secondaryPress();for(let i=0;i<60;i++)sim.update(1/60);assert.ok(sim.state.carried.dust>0);sim.secondaryRelease();sim.rebuildShowcase();
        const displayWorker=sim.state.workers.find(item=>item.job==="guard"),nearDrop=sim.resourceDrops[0],displayEnemy=sim.state.enemies[0];displayWorker.hp=sim.TUNE.fleeHpThreshold;displayWorker.fleeing=false;displayWorker.returnAfterCombat=true;displayWorker.reposting=true;displayWorker.carried.wood=0;nearDrop.x=displayWorker.x;nearDrop.y=displayWorker.y;nearDrop.ground=true;nearDrop.target=null;delete nearDrop.claimedBy;displayEnemy.x=displayWorker.x;displayEnemy.y=displayWorker.y;const inactiveSnapshot={x:displayWorker.x,y:displayWorker.y,fleeing:displayWorker.fleeing,returnAfterCombat:displayWorker.returnAfterCombat,reposting:displayWorker.reposting,drops:sim.resourceDrops.length,wood:displayWorker.carried.wood};for(let i=0;i<10;i++)sim.update(1/60);assert.deepEqual({x:displayWorker.x,y:displayWorker.y,fleeing:displayWorker.fleeing,returnAfterCombat:displayWorker.returnAfterCombat,reposting:displayWorker.reposting,drops:sim.resourceDrops.length,wood:displayWorker.carried.wood},inactiveSnapshot);
        const elapsed=sim.state.clock.elapsed;sim.togglePause();for(let i=0;i<60;i++)sim.update(1/60);assert.equal(sim.state.clock.elapsed,elapsed);sim.togglePause();
        sim.pressKey("KeyD");for(let i=0;i<9000;i++){if(i===300)sim.releaseKey("KeyD");sim.update(1/60);if(i%120===0)check();}check();assert.ok(sim.damageDummies.some(item=>item.hitCount>0));
        sim.resetShowcaseProps();sim.resetDamageDummies();check();
        console.log(JSON.stringify({...expected,steps:9000,labels:sim.showcaseLabels().labels.length}));
      }finally{Math.random=old;}
    `
  }).trim());

  console.log(`validate ok | syntax ${jsFiles.length} | feature ${featureResult.checks} checks | normal ${normalSteps} steps | showcase ${showcaseResult.steps} steps | fixtures ${showcaseResult.buildings} buildings, ${showcaseResult.dummies} dummies, ${showcaseResult.props} props, ${showcaseResult.enemies} enemies, ${showcaseResult.workers} workers | skills ${skills.length} | labels ${showcaseResult.labels}`);
}finally{
  Math.random=originalRandom;
}
